services:
  api:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
      REDIS_HOST: redis
    expose:
      - 8000
    command: ["fastapi", "run", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "strong"
      POSTGRES_DB: "fastship"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data

  celery:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
      REDIS_HOST: redis
    command: ["celery", "-A", "app.worker.tasks", "worker", "--loglevel=info"]
    depends_on:
      - db
      - redis
